stages:
  - build
  - test

.base:
  image: ruby:3.0.5
  cache:
    key: gems_and_packages
    paths:
      - apt-cache/
      - vendor/ruby
    policy: pull
  before_script:
    - gem install bundler --no-document
    - bundle check || bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor --without development production

.base_db:
  extends: .base
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: database_name
    POSTGRES_PASSWORD: supersecurepassword
    DATABASE_URL: "postgresql://postgres:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB"
    RAILS_ENV: test
    DISABLE_SPRING: 1
  before_script:
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor --without development production
    - bin/rails db:create db:migrate
    - bin/rails db:seed

build:rubocop:
  extends: .base
  stage: build
  cache:
    policy: pull-push
  script:
    - bundle exec rubocop

test:rspec:
  extends: .base_db
  stage: test
  script:
    - SPEC_OPTS="--tag ~focus" bundle exec rspec spec
